import AppKit
import ImageIO
import WinnelCore

public enum CaptureResult: Sendable {
    case captured(ClipPayload, SourceApplication)
    case skipped(CaptureSkipReason)
}
public enum CaptureSkipReason: String, Sendable { case excluded, marker, changed, unsupported, oversized, invalidImage, unavailable, permissionDenied, permissionRequired }

public enum ClipboardAccessStatus: String, Sendable { case allowed, required, denied }

public struct CapturePolicy: Sendable {
    public static let allowedTypes = ["public.utf8-plain-text", "public.text", "public.url", "public.rtf", "public.png", "public.tiff", "public.jpeg", "public.file-url"]
    public static let blockedMarkers: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.AutoGenerated", "com.apple.is-remote-clipboard", "com.madeordinary.winnel.own-write"]
    public var byteLimit = 20 * 1024 * 1024
    public var dimensionLimit = 8192
    public var pixelLimit = 32_000_000
    public init() {}
    public func permits(source: String?, previous: String?, excluded: Set<String>) -> Bool {
        !excluded.contains(source ?? "") && !excluded.contains(previous ?? "")
    }
    public func permitsImage(_ data: Data) -> Bool {
        guard let source = CGImageSourceCreateWithData(data as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
              CGImageSourceGetCount(source) == 1,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int,
              width > 0, height > 0, width <= dimensionLimit, height <= dimensionLimit else { return false }
        return width <= pixelLimit / height
    }
    /// Reads only the image header to name an admitted image, e.g. "PNG image · 1200 × 800".
    public func imageDescriptor(_ data: Data, type: String) -> String? {
        let format: String
        switch type { case "public.png": format = "PNG"; case "public.tiff": format = "TIFF"; case "public.jpeg": format = "JPEG"; default: return nil }
        guard let source = CGImageSourceCreateWithData(data as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int, width > 0, height > 0 else { return "\(format) image" }
        return "\(format) image · \(width) × \(height)"
    }
    /// A conservative lexical allowlist gates Apple's RTF reader. External/resource
    /// destinations, binary data and embedded objects are excluded before parsing.
    /// The platform parser supplies text fidelity; this gate does not interpret RTF text.
    public func plainTextFromSafeRTF(_ data: Data) -> String? {
        guard data.count <= byteLimit, data.starts(with: Data("{\\rtf".utf8)) else { return nil }
        let safeWords: Set<String> = ["rtf", "ansi", "mac", "pc", "pca", "ansicpg", "deff", "deflang", "deflangfe", "uc", "u",
            "fonttbl", "colortbl", "stylesheet", "f", "fnil", "froman", "fswiss", "fmodern", "fscript", "fdecor", "ftech", "fbidi", "fcharset", "fprq", "cpg",
            "red", "green", "blue", "s", "cs", "sbasedon", "snext", "additive", "sautoupd",
            "b", "i", "ul", "ulnone", "strike", "striked", "plain", "pard", "par", "line", "tab", "fs", "cf", "cb", "highlight",
            "ql", "qr", "qc", "qj", "li", "ri", "fi", "sa", "sb", "sl", "slmult", "tx", "tqc", "tqr", "tqdec", "rtlpar", "ltrpar", "rtlch", "ltrch",
            "super", "sub", "nosupersub", "caps", "scaps", "outl", "shad", "expnd", "expndtw", "kerning", "lang", "langfe", "loch", "hich", "dbch", "af",
            "emdash", "endash", "emspace", "enspace", "qmspace", "bullet", "lquote", "rquote", "ldblquote", "rdblquote",
            "paperw", "paperh", "margl", "margr", "margt", "margb", "vieww", "viewh", "viewkind", "viewscale", "fet",
            "cocoartf", "cocoasubrtf", "cocoatextscaling", "cocoaplatform"]
        let bytes = [UInt8](data)
        var index = 0, depth = 0
        while index < bytes.count {
            let byte = bytes[index]; index += 1
            if byte == 123 { depth += 1; guard depth <= 128 else { return nil } }
            else if byte == 125 { depth -= 1; guard depth >= 0 else { return nil } }
            else if byte == 92 {
                guard index < bytes.count else { return nil }
                let start = index
                while index < bytes.count, (65...90).contains(bytes[index]) || (97...122).contains(bytes[index]) { index += 1 }
                if index > start {
                    let word = String(decoding: bytes[start..<index], as: UTF8.self)
                    guard safeWords.contains(word) else { return nil }
                } else {
                    // Only standard character/control escapes; no arbitrary destination symbols.
                    guard [92, 123, 125, 39, 42, 126, 45, 95, 10, 13].contains(bytes[index]) else { return nil }
                    index += 1
                }
            }
        }
        guard depth == 0, let parsed = try? NSAttributedString(data: data,
            options: [.documentType: NSAttributedString.DocumentType.rtf], documentAttributes: nil),
            parsed.string.utf8.count <= byteLimit else { return nil }
        // Defensive second boundary: the permitted subset should never yield an attachment.
        var attachment = false
        parsed.enumerateAttribute(.attachment, in: NSRange(location: 0, length: parsed.length)) { value, _, stop in
            if value != nil { attachment = true; stop.pointee = true }
        }
        return attachment ? nil : parsed.string
    }
    public func serializedSize(_ payload: ClipPayload) -> Int? { try? JSONEncoder().encode(payload).count }
    /// Run away from the main actor. Metadata limits are checked before ImageIO decodes pixels.
    public func thumbnail(_ data: Data, maximumDimension: Int = 256) -> Data? {
        guard permitsImage(data), maximumDimension > 0, maximumDimension <= 512,
              let source = CGImageSourceCreateWithData(data as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
              let image = CGImageSourceCreateThumbnailAtIndex(source, 0, [kCGImageSourceCreateThumbnailFromImageAlways: true, kCGImageSourceThumbnailMaxPixelSize: maximumDimension, kCGImageSourceShouldCacheImmediately: true] as CFDictionary) else { return nil }
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(output, "public.png" as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        return CGImageDestinationFinalize(destination) ? output as Data : nil
    }
}

public enum FileReferenceMetadata {
    /// User-directed preview/export only: consult filesystem existence, never read file contents.
    public static func resolve(_ reference: FileReference) -> FileReference {
        var result = reference
        guard let url = URL(string: reference.urlString) else { result.availability = .unavailable; return result }
        guard url.scheme != nil, url.path.hasPrefix("/") else { result.availability = .relative; return result }
        guard url.isFileURL, url.host == nil || url.host == "" || url.host == "localhost" else { result.availability = .unavailable; return result }
        result.availability = FileManager.default.fileExists(atPath: url.path) ? .available : .unavailable
        return result
    }
}

@MainActor public final class PasteboardService {
    public static let ownMarker = NSPasteboard.PasteboardType("com.madeordinary.winnel.own-write")
    public let pasteboard: NSPasteboard
    public var policy: CapturePolicy
    public var changeCount: Int { pasteboard.changeCount }
    public var permissionStatus: ClipboardAccessStatus { SnapshotRead.permissionStatus(pasteboard) }
    /// Only call from a deliberate UI action. Discard the probe; never capture the old clipboard.
    /// macOS controls whether it prompts, allows this user action, or keeps automatic access denied.
    public func requestAccessFromUserAction() -> ClipboardAccessStatus {
        _ = pasteboard.data(forType: .string)
        return permissionStatus
    }
    public init(pasteboard: NSPasteboard = .general, policy: CapturePolicy = .init()) { self.pasteboard = pasteboard; self.policy = policy }
    public func readSnapshot(source: SourceApplication = .init(), excluded: Set<String> = [], previousForegroundID: String? = nil) -> CaptureResult {
        SnapshotRead.read(pasteboard: pasteboard, policy: policy, source: source, excluded: excluded, previousForegroundID: previousForegroundID)
    }
    @discardableResult public func write(_ payload: ClipPayload) -> Bool {
        guard let size = policy.serializedSize(payload), size <= policy.byteLimit else { return false }
        let item = NSPasteboardItem()
        item.setData(Data(), forType: Self.ownMarker)
        for value in payload.representations where CapturePolicy.allowedTypes.contains(value.type) { item.setData(value.data, forType: .init(value.type)) }
        var items = payload.representations.contains(where: { CapturePolicy.allowedTypes.contains($0.type) }) ? [item] : []
        for file in payload.fileReferences {
            guard let url = URL(string: file.urlString), url.isFileURL else { continue }
            let reference = NSPasteboardItem()
            reference.setData(Data(), forType: Self.ownMarker)
            reference.setString(file.urlString, forType: .fileURL)
            items.append(reference)
        }
        guard !items.isEmpty else { return false }
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        return pasteboard.writeObjects(items)
    }
    @discardableResult public func clear(expectedChangeCount: Int) -> Bool {
        guard changeCount == expectedChangeCount else { return false }
        // No atomic compare-and-clear API exists. Recheck immediately before the mutation;
        // another process can still race between this check and the OS call.
        guard pasteboard.changeCount == expectedChangeCount else { return false }
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        return true
    }
}

/// A serialized reader owns each NSPasteboard proxy on its own actor executor. Only its
/// name and immutable policy/context cross isolation boundaries, never AppKit objects.
public actor PasteboardSnapshotReader {
    private let name: String
    public init(name: String) { self.name = name }
    public func read(policy: CapturePolicy, source: SourceApplication, excluded: Set<String>, previousForegroundID: String?) -> CaptureResult {
        guard !Task.isCancelled else { return .skipped(.changed) }
        let board = NSPasteboard(name: NSPasteboard.Name(name))
        return SnapshotRead.read(pasteboard: board, policy: policy, source: source, excluded: excluded, previousForegroundID: previousForegroundID)
    }
}
private enum SnapshotRead {
    static func permissionStatus(_ pasteboard: NSPasteboard) -> ClipboardAccessStatus {
        if #available(macOS 15.4, *) {
            switch pasteboard.accessBehavior {
            case .alwaysDeny: return .denied
            case .ask: return .required
            case .default: return pasteboard.name == .general ? .required : .allowed
            case .alwaysAllow: return .allowed
            @unknown default: return .required
            }
        }
        return .allowed
    }
    static func read(pasteboard: NSPasteboard, policy: CapturePolicy, source: SourceApplication, excluded: Set<String>, previousForegroundID: String?) -> CaptureResult {
        guard policy.permits(source: source.bundleIdentifier, previous: previousForegroundID, excluded: excluded) else { return .skipped(.excluded) }
        switch permissionStatus(pasteboard) {
        case .denied: return .skipped(.permissionDenied)
        case .required: return .skipped(.permissionRequired)
        case .allowed: break
        }
        let count = pasteboard.changeCount
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return .skipped(.unavailable) }
        // Inspect all advertised markers before asking any provider for payload data.
        let types = items.map { $0.types }
        guard !types.joined().contains(where: { CapturePolicy.blockedMarkers.contains($0.rawValue) }) else { return .skipped(.marker) }
        let fileOnly = items.count > 1 && types.allSatisfy { $0.contains(.fileURL) }
        // Domain payload stores one representation set. Avoid flattening multiple distinct
        // text/image items into an apparently faithful single item; ordered file references
        // are the supported multiple-item exception.
        guard items.count == 1 || fileOnly else { return .skipped(.unsupported) }
        var acquired = ClipPayload()
        var estimated = 128
        for (index, item) in items.enumerated() {
            for raw in (fileOnly ? ["public.file-url"] : CapturePolicy.allowedTypes) where types[index].contains(NSPasteboard.PasteboardType(raw)) {
                // NSPasteboard exposes no preflight byte length: data(forType:) can allocate a
                // provider's entire representation. The following bounds limit retention and
                // decoding, not the system/provider allocation. Never request unknown types.
                guard !Task.isCancelled else { return .skipped(.changed) }
                guard let data = item.data(forType: NSPasteboard.PasteboardType(raw)) else { continue }
                guard data.count <= policy.byteLimit, data.count <= (policy.byteLimit - estimated) / 4 * 3 else { return .skipped(.oversized) }
                estimated += ((data.count + 2) / 3) * 4 + raw.utf8.count + 64
                acquired.representations.append(.init(type: raw, data: data))
            }
        }
        // Admit the complete serialized input before any content parser runs. Derived
        // text/file metadata has a separate exact admission gate before publication.
        guard let acquiredSize = policy.serializedSize(acquired), acquiredSize <= policy.byteLimit else { return .skipped(.oversized) }
        var payload = ClipPayload()
        for representation in acquired.representations {
            let raw = representation.type, data = representation.data
            guard !Task.isCancelled else { return .skipped(.changed) }
            if ["public.png", "public.tiff", "public.jpeg"].contains(raw), !policy.permitsImage(data) { return .skipped(.invalidImage) }
            if raw == "public.file-url" {
                guard let string = String(data: data, encoding: .utf8), let url = URL(string: string), url.isFileURL else { continue }
                payload.fileReferences.append(.init(urlString: string, displayName: url.lastPathComponent, availability: .unknown))
            } else if raw == "public.rtf" {
                guard let text = policy.plainTextFromSafeRTF(data) else { continue }
                payload.representations.append(.init(type: raw, data: data))
                if payload.plainText == nil {
                    payload.representations.append(.init(type: "public.utf8-plain-text", data: Data(text.utf8)))
                }
            } else { payload.representations.append(.init(type: raw, data: data)) }
        }
        guard pasteboard.changeCount == count, let settled = pasteboard.pasteboardItems,
              settled.count == items.count, settled.map({ $0.types }) == types else { return .skipped(.changed) }
        guard !settled.flatMap({ $0.types }).contains(where: { CapturePolicy.blockedMarkers.contains($0.rawValue) }) else { return .skipped(.marker) }
        guard !payload.representations.isEmpty || !payload.fileReferences.isEmpty else { return .skipped(.unsupported) }
        guard let size = policy.serializedSize(payload), size <= policy.byteLimit else { return .skipped(.oversized) }
        return .captured(payload, source)
    }
}
